### PR TITLE
Update of dependencies and support for Python3.10 to Python3.13

### LINKED ISSUE #160: Prance doesn't work with python 3.12.1
## Expected Behaviour
Spec should get validated for valid swagger file.

### Minimal Example Spec
- http://petstore.swagger.io/v2/swagger.json

## Actual Behaviour
Raises AttributeError: '_io.BufferedReader' object has no attribute 'decode'

## Steps to Reproduce
- Execute below command:

```bash
$ prance validate http://petstore.swagger.io/v2/swagger.json
Processing "http://petstore.swagger.io/v2/swagger.json"...
 -> Resolving external references.
Traceback (most recent call last):
  File "/Users/apple/.pyenv/versions/3.12.1/bin/prance", line 8, in <module>
    sys.exit(cli())
             ^^^^^
  File "/Users/apple/.pyenv/versions/3.12.1/lib/python3.12/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/apple/.pyenv/versions/3.12.1/lib/python3.12/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/Users/apple/.pyenv/versions/3.12.1/lib/python3.12/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/apple/.pyenv/versions/3.12.1/lib/python3.12/site-packages/prance/cli.py", line 114, in command_invoke
    original_invoke(ctx)
  File "/Users/apple/.pyenv/versions/3.12.1/lib/python3.12/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/apple/.pyenv/versions/3.12.1/lib/python3.12/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/apple/.pyenv/versions/3.12.1/lib/python3.12/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/apple/.pyenv/versions/3.12.1/lib/python3.12/site-packages/prance/cli.py", line 209, in validate
    __validate(parser, name)
  File "/Users/apple/.pyenv/versions/3.12.1/lib/python3.12/site-packages/prance/cli.py", line 65, in __validate
    parser.parse()
  File "/Users/apple/.pyenv/versions/3.12.1/lib/python3.12/site-packages/prance/__init__.py", line 148, in parse
    self._validate()
  File "/Users/apple/.pyenv/versions/3.12.1/lib/python3.12/site-packages/prance/__init__.py", line 316, in _validate
    BaseParser._validate(self)
  File "/Users/apple/.pyenv/versions/3.12.1/lib/python3.12/site-packages/prance/__init__.py", line 187, in _validate
    validator(parsed)
  File "/Users/apple/.pyenv/versions/3.12.1/lib/python3.12/site-packages/prance/__init__.py", line 248, in _validate_openapi_spec_validator
    validate_spec(self.specification)
  File "/Users/apple/.pyenv/versions/3.12.1/lib/python3.12/site-packages/openapi_spec_validator/shortcuts.py", line 17, in validate_spec
    return validator.validate(spec, spec_url=spec_url)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/apple/.pyenv/versions/3.12.1/lib/python3.12/site-packages/openapi_spec_validator/validation/proxies.py", line 27, in validate
    for err in validator.iter_errors(instance, spec_url=spec_url):
  File "/Users/apple/.pyenv/versions/3.12.1/lib/python3.12/site-packages/openapi_spec_validator/validation/decorators.py", line 22, in wrapper
    for err in errors:
  File "/Users/apple/.pyenv/versions/3.12.1/lib/python3.12/site-packages/openapi_spec_validator/validation/validators.py", line 89, in iter_errors
    yield from self.schema_validator.iter_errors(instance)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<attrs generated init jsonschema.validators.create.<locals>.Validator>", line 5, in __init__
  File "/Users/apple/.pyenv/versions/3.12.1/lib/python3.12/site-packages/jsonschema/validators.py", line 216, in __attrs_post_init__
    self.resolver = RefResolver.from_schema(
                    ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/apple/.pyenv/versions/3.12.1/lib/python3.12/site-packages/jsonschema/validators.py", line 772, in from_schema
    return cls(base_uri=id_of(schema), referrer=schema, *args, **kwargs)  # noqa: B026, E501
                        ^^^^^^^^^^^^^
  File "/Users/apple/.pyenv/versions/3.12.1/lib/python3.12/site-packages/jsonschema/_legacy_validators.py", line 12, in id_of
    if schema is True or schema is False or "$ref" in schema:
                                            ^^^^^^^^^^^^^^^^
  File "/Users/apple/.pyenv/versions/3.12.1/lib/python3.12/site-packages/openapi_spec_validator/schemas/utils.py", line 28, in get_schema_content
    content, _ = get_schema(version)
                 ^^^^^^^^^^^^^^^^^^^
  File "/Users/apple/.pyenv/versions/3.12.1/lib/python3.12/site-packages/openapi_spec_validator/schemas/utils.py", line 24, in get_schema
    return FilePathReader(schema_path_full).read()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/apple/.pyenv/versions/3.12.1/lib/python3.12/site-packages/jsonschema_spec/readers.py", line 37, in read
    return all_urls_handler(uri), uri
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/apple/.pyenv/versions/3.12.1/lib/python3.12/site-packages/jsonschema_spec/handlers/file.py", line 45, in __call__
    return self._open(uri)
           ^^^^^^^^^^^^^^^
  File "/Users/apple/.pyenv/versions/3.12.1/lib/python3.12/site-packages/jsonschema_spec/handlers/urllib.py", line 18, in _open
    return super().__call__(fh)
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/apple/.pyenv/versions/3.12.1/lib/python3.12/site-packages/jsonschema_spec/handlers/file.py", line 41, in __call__
    parsed_url = urlparse(uri)
                 ^^^^^^^^^^^^^
  File "/Users/apple/.pyenv/versions/3.12.1/lib/python3.12/urllib/parse.py", line 394, in urlparse
    url, scheme, _coerce_result = _coerce_args(url, scheme)
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/apple/.pyenv/versions/3.12.1/lib/python3.12/urllib/parse.py", line 133, in _coerce_args
    return _decode_args(args) + (_encode_result,)
           ^^^^^^^^^^^^^^^^^^
  File "/Users/apple/.pyenv/versions/3.12.1/lib/python3.12/urllib/parse.py", line 117, in _decode_args
    return tuple(x.decode(encoding, errors) if x else '' for x in args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/apple/.pyenv/versions/3.12.1/lib/python3.12/urllib/parse.py", line 117, in <genexpr>
    return tuple(x.decode(encoding, errors) if x else '' for x in args)
                 ^^^^^^^^
  File "/Users/apple/.pyenv/versions/3.12.1/lib/python3.12/tempfile.py", line 494, in __getattr__
    a = getattr(file, name)
        ^^^^^^^^^^^^^^^^^^^
AttributeError: '_io.BufferedReader' object has no attribute 'decode'
```

## Environment
- OS: MacOS
- Python version: 3.12.1
- Swagger/OpenAPI version used: 2.0 (http://petstore.swagger.io/v2/swagger.json)
- Backend: (flex, swagger-spec-validator or openapi-spec-validator)

### PR DESCRIPTION
**Pull request by MathisFranel**
Fixes #160.

Changes proposed in this PR:
-Added support for Python3.12 and 3.13
-Removed support for Python3.8 and 3.9
-Replaced down https://mermade.org.uk/ API by https://converter.swagger.io/ for converting from Swagger/OpenAPI 2.0 to OpenAPI 3.0.0
-Replace down http://finkhaeuser.de/projects/prance/petstore.yaml by https://petstore.swagger.io/v2/swagger.yaml
-Replace deprecated RefResolutionError and validate_spec in BaseParser
-Added skipif for flex related tests (+coverage 89 due to more skipped tests) + backend specified for openapi-spec-validator related tests
-Update of project dependencies

prance test OK
The coverage for flex is at 89.5% and at 98.87% for other cases
image

### CODE REVIEW

**Comment by MathisFranel** [comment]
Hi @RonnyPfannschmidt,
Could you check this one please? It could help on few other projects that rely on your work.
Thanks in advance!

**Comment by RonnyPfannschmidt** [comment]
Thanks for getting this started 

At first glance it looks like ill have to schedule a time block for review

**Comment by fwininger** [comment]
Thanks @MathisFranel

**Comment by RonnyPfannschmidt** [comment]
I'm down with a cold since a few days so getting this in currently is delayed

**Comment by MathisFranel** [comment]
Hi @RonnyPfannschmidt,
Have you had time to check the PR?

**Comment by RonnyPfannschmidt** [comment]
Nope had a flu that kept me down quite a while and I'm still catching up

**Comment by dseichter** [comment]
Hope you're getting well soon!
This PR will also fix my open report #162. Within an isolated environment, also the vulnerability scan tool Wapiti, will worked, if this PR will be merged and used for the next upcoming release of prance.

**Comment by MathisFranel** [comment]
Hi @RonnyPfannschmidt,
I hope you are doing well, is it possible for you to check the PR, if you got some free time?

File: setup.cfg [hunk 1]
```diff
@@ -28,13 +29,14 @@ license = MITNFA
...
-    chardet>=3.0
-    ruamel.yaml>=0.17.10
-    requests>=2.25
-    six~=1.15
-    packaging>=21.3
+    setuptools>=75.8.0
+    chardet>=5.2
+    ruamel.yaml>=0.18.10
+    requests>=2.32.3
+    six~=1.17
```
Comment (RonnyPfannschmidt) [inline setup.cfg:36]: six should be removed , but a followup is fine

File: setup.cfg [hunk 2]
```diff
@@ -28,13 +29,14 @@ license = MITNFA
 packages = find:
 include_package_data = True
 install_requires =
-    chardet>=3.0
-    ruamel.yaml>=0.17.10
-    requests>=2.25
-    six~=1.15
-    packaging>=21.3
+    setuptools>=75.8.0
```
Comment (RonnyPfannschmidt) [inline setup.cfg:32]: setuptools shouldnt be part of the install requires

**Review by RonnyPfannschmidt — CHANGES_REQUESTED** [review]
thanks for gettign this started

six removal and full pyproject migration can be followups

is there a specific reason for going to setuptools>75?

File: setup.cfg (hunk 2 above)
Comment (MathisFranel) [reply setup.cfg:32]: There is no specific reason tbh it was just the newest version at this time but we can keep it at 60 like it was before, I think that the install of setuptools is required for python 3.12 because [pkg_resources has been removed from default python](https://docs.python.org/3/whatsnew/3.12.html)

Comment (RonnyPfannschmidt) [reply setup.cfg:32]: ah, so a importlib.resources migration is missing, in that case we need to keep setuptools until we migrate to importlib-resources

leaving the option for a version older is a nice add as this eases install in environments where system setuptools is enterprise ancient

Comment (RonnyPfannschmidt) [reply setup.cfg:32]: it seems there is a single simple usage https://github.com/RonnyPfannschmidt/prance/blob/2b91d0776630512843ca7d2975f963080a5c3bb6/prance/util/url.py#L197C30-L197C47

i beleive thats very easy to replace with https://docs.python.org/3/library/importlib.resources.html#importlib.resources.read_text

Comment (MathisFranel) [reply setup.cfg]: thanks a lot for the information, I fixed it, now it should be fine.

File: prance/util/url.py [hunk 3]
```diff
@@ -192,9 +192,9 @@ def fetch_url_text(url, cache={}, encoding=None):
         if path[0] == "/":
             path = path[1:]
 
-        import pkg_resources
+        from importlib import resources
```
Comment (RonnyPfannschmidt) [inline prance/util/url.py:195]: Given the content is read content let's skip the fa helpers

Comment (RonnyPfannschmidt) [reply prance/util/url.py:195]: Importlib resources has an api for directly getting content 

Precisely the spi u linked to

We should use it directly

Comment (MathisFranel) [reply prance/util/url.py]: I did the changes

**Review by RonnyPfannschmidt — APPROVED** [review]

**Comment by RonnyPfannschmidt** [comment]
I'll try to do a merge plus release on Monday 

Not going to try luck Friday evening
